- name: PLAY1
  hosts: localhost
  connection: local
  tasks:
    - name: hello from play 1 and task1
      ansible.builtin.debug:
        msg: "Hello from play 1 and task1"

    - name: hello from play 1 and task2
      ansible.builtin.debug:
        msg: "Hello from play 1 and task2"

- name: PLAY2
  hosts: localhost
  connection: local
  tasks:
    - name: hello from play 2 and task1
      ansible.builtin.debug:
        msg: "Hello from play 2 and task1"
    
    - name: hello from play 2 and task2
      ansible.builtin.debug:
        msg: "Hello from play 2 and task2"
