- name: play level variables
  hosts: local
  connection: local
  vars:
   course: "DevOps ansible"
   duration: "8.23 HR"
   trainer: sk"
  tasks:
  - name: print course infromation
    ansbible.builtin.debug:
      mgs: "course is trained by trainer {{ trainer }} for duartion of  {{ duration }} in subject {{ course }}"

  - name: print course infromation
    vars:
      course: "Ansible"
      trainer: "John Doe"
      duration: "5.5 HR"
    ansible.builtin.debug:
      msg: "course is trained by trainer {{ trainer }} for duartion of  {{ duration }} in subject {{ course }}"
