- name: variable from files
  hosts: local 
  connection: local
  vars_files:
    - course.yaml
  tasks:
  - name: print course infromation
    ansible.builtin.debug:
      msg: "Learning {{ COURSE }} with duration of {{ DURATION }}"