- name: variables from inventory
  hosts: local 
  connection: local
  tasks:
  - name: print inventory variables
    ansbile.builtin.debug:
      msg: "the trainer was {{TRAINER}} duration was {{DURATION}} and the subject was {{COURSE}}"
      