- name: written password, user and variables in inventory
  hosts: frontend
  tasks:
  - name: print course infromation
    ansible.builtin.debug:
      msg: "the trainer was {{TRAINER}} duration was {{DURATION}} and the subject was {{COURSE}}"