- name: functions
  hosts: local
  connection: local
  vars:
    person: "dimitri, petrenko, peter "  # Define a variable 'person' with a default value
  tasks:
  - name: check undefined variable
    ansible.builtin.debug:
      msg: "Hello, {{ person | default('ethan hunt') }}"

  - name: print name
    ansible.builtin.debug:
      msg:  " hola, {{ person | split(', ')}}"

  - name: convert map into list
    vars:
      course:
        name: ansible
        duration: 10HR
        trainer: sk
    ansible.builtin.debug:
      msg: "course info: {{ course| dict2items }}"